version: '3'
services:
  php1:
    image: php:fpm
    container_name: php-fpm_service
    expose:
      - "9000"
    networks:
      - "starlab-net1"
    volumes:
      - "/starlab/docker/php:/app"

networks:
  starlab-net1:
    driver: bridge
    